
const db=supabase.createClient(APP_CONFIG.SUPABASE_URL,APP_CONFIG.SUPABASE_KEY);
const langs=[['it','Italiano'],['en','English'],['fr','Français'],['es','Español'],['de','Deutsch'],['pt','Português'],['ru','Русский'],['ar','العربية'],['zh','中文'],['ja','日本語'],['ko','한국어'],['pl','Polski'],['sq','Shqip'],['ro','Română'],['hu','Magyar'],['nl','Nederlands'],['hr','Hrvatski'],['el','Ελληνικά'],['tr','Türkçe']];
const allergens={gluten:'Glutine',crustaceans:'Crostacei',eggs:'Uova',fish:'Pesce',peanuts:'Arachidi',soy:'Soia',milk:'Latte e derivati',nuts:'Frutta a guscio',celery:'Sedano',mustard:'Senape',sesame:'Sesamo',sulphites:'Solfiti',lupin:'Lupini',molluscs:'Molluschi'};
const nuts={almond:'Mandorla',hazelnut:'Nocciola',walnut:'Noce',pistachio:'Pistacchio',pine_nut:'Pinolo',cashew:'Anacardio',pecan:'Noce pecan',brazil_nut:'Noce del Brasile',macadamia:'Macadamia'};
let products=[], translations={}, current=null, filter='all';
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toggleRow(id,label){return `<div class="toggleline"><span>${label}</span><label class="switch"><input id="${id}" type="checkbox"><span class="slider"></span></label></div>`}
$('toggles').innerHTML=toggleRow('is_available','Disponibile')+toggleRow('is_bestseller','Bestseller')+toggleRow('is_vegan','Vegana')+toggleRow('is_vegetarian','Vegetariana')+toggleRow('is_lactose_free','Senza lattosio')+toggleRow('is_spicy','Piccante');
$('allergenChecks').innerHTML=Object.entries(allergens).map(([k,v])=>`<label class="check"><input type="checkbox" name="allergen" value="${k}">${v}</label>`).join('');
$('nutChecks').innerHTML=Object.entries(nuts).map(([k,v])=>`<label class="check"><input type="checkbox" name="nut" value="${k}">${v}</label>`).join('');
$('translations').innerHTML=langs.filter(x=>x[0]!=='it').map(([c,n])=>`<div class="card"><h3>${n} (${c.toUpperCase()})</h3><div class="field"><label>Descrizione ingredienti</label><textarea class="${c==='ar'?'rtl':''}" data-lang-desc="${c}"></textarea></div></div>`).join('');
document.querySelector('[name=allergen][value=nuts]').addEventListener('change',e=>$('nutBlock').classList.toggle('hidden',!e.target.checked));
$('is_vegan').addEventListener('change',e=>{if(e.target.checked)$('is_vegetarian').checked=true});
$('is_vegetarian').addEventListener('change',e=>{if(!e.target.checked&&$('is_vegan').checked){e.target.checked=true;alert('Una proposta vegana deve restare anche vegetariana.')}});
async function init(){const {data:{session}}=await db.auth.getSession(); if(session) showApp(); db.auth.onAuthStateChange((_e,s)=>s?showApp():showLogin())}
async function showApp(){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');await load()}
function showLogin(){$('appView').classList.add('hidden');$('loginView').classList.remove('hidden')}
$('loginBtn').onclick=async()=>{ $('loginMsg').textContent=''; const {error}=await db.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value}); if(error)$('loginMsg').textContent=error.message };
$('logoutBtn').onclick=()=>db.auth.signOut(); $('refreshBtn').onclick=load; $('newBtn').onclick=()=>openEditor(); $('closeEditor').onclick=closeEditor;
document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;render()}); $('search').oninput=render;
async function load(){ $('list').innerHTML='<div class="loading">Caricamento…</div>'; const {data:p,error:e}=await db.from('products').select('*').order('category').order('display_order'); if(e)return $('list').innerHTML='<div class="error">'+esc(e.message)+'</div>'; products=p||[]; const {data:t,error:te}=await db.from('product_translations').select('*'); if(te)return $('list').innerHTML='<div class="error">'+esc(te.message)+'</div>'; translations={}; (t||[]).forEach(x=>{translations[x.product_id]??={};translations[x.product_id][x.language_code]=x}); render() }
function render(){const q=$('search').value.toLowerCase().trim(); let a=products.filter(p=>filter==='all'||p.category===filter||(filter==='draft'&&p.publication_status==='draft')); a=a.filter(p=>{const n=translations[p.id]?.it?.name||p.internal_code||'';return n.toLowerCase().includes(q)}); $('list').innerHTML=a.length?a.map(card).join(''):'<div class="loading">Nessun risultato</div>'; document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(b.dataset.edit)); document.querySelectorAll('[data-avail]').forEach(s=>s.onchange=()=>setAvailability(s.dataset.avail,s.checked))}
function card(p){const it=translations[p.id]?.it||{};return `<div class="card"><div class="row"><div><div class="name">${esc(it.name||p.internal_code||'Senza nome')}</div><div class="desc">${esc(it.description||'')}</div><div class="meta">${p.category==='dolce'?'Dolce':'Salata'} · ${p.publication_status==='draft'?'Bozza':'Pubblicata'}</div></div><div><div class="price">${Number(p.price).toFixed(2)} €</div><label class="switch" style="margin-top:10px"><input data-avail="${p.id}" type="checkbox" ${p.is_available?'checked':''}><span class="slider"></span></label></div></div><div class="actions"><button class="btn small" data-edit="${p.id}">Modifica</button></div></div>`}
async function setAvailability(id,val){const {error}=await db.from('products').update({is_available:val}).eq('id',id); if(error){alert(error.message);await load()} else {const p=products.find(x=>x.id===id);if(p)p.is_available=val}}
function openEditor(id=null){current=id?products.find(p=>p.id===id):null;$('editorTitle').textContent=current?'MODIFICA FOCACCIA':'NUOVA FOCACCIA';$('deleteBtn').classList.toggle('hidden',!current);$('editMsg').innerHTML='';const p=current||{category:'salata',price:'',display_order:products.filter(x=>x.category==='salata').length+1,publication_status:'draft',is_available:true};['internal_code','price','category','display_order'].forEach(k=>$(k).value=p[k]??'');['is_available','is_bestseller','is_vegan','is_vegetarian','is_lactose_free','is_spicy'].forEach(k=>$(k).checked=!!p[k]);document.querySelectorAll('[name=allergen]').forEach(c=>c.checked=(p.allergens||[]).includes(c.value));document.querySelectorAll('[name=nut]').forEach(c=>c.checked=(p.nut_types||[]).includes(c.value));$('nutBlock').classList.toggle('hidden',!(p.allergens||[]).includes('nuts'));const tr=current?translations[current.id]||{}:{};$('name_it').value=tr.it?.name||'';$('description_it').value=tr.it?.description||'';langs.filter(x=>x[0]!=='it').forEach(([c])=>{document.querySelector(`[data-lang-desc="${c}"]`).value=tr[c]?.description||''});$('editor').classList.remove('hidden')}
function closeEditor(){$('editor').classList.add('hidden');current=null}
function payload(status){const allergensArr=[...document.querySelectorAll('[name=allergen]:checked')].map(x=>x.value);const nutArr=allergensArr.includes('nuts')?[...document.querySelectorAll('[name=nut]:checked')].map(x=>x.value):[];return {internal_code:$('internal_code').value.trim()||null,category:$('category').value,price:Number($('price').value),display_order:Number($('display_order').value||0),publication_status:status,is_available:$('is_available').checked,is_bestseller:$('is_bestseller').checked,is_vegan:$('is_vegan').checked,is_vegetarian:$('is_vegetarian').checked,is_lactose_free:$('is_lactose_free').checked,is_spicy:$('is_spicy').checked,allergens:allergensArr,nut_types:nutArr}}
async function save(status){$('editMsg').innerHTML='';if(!$('name_it').value.trim()||!$('price').value)return $('editMsg').innerHTML='<p class="error">Nome italiano e prezzo sono obbligatori.</p>';let id=current?.id;const data=payload(status);let r;if(id)r=await db.from('products').update(data).eq('id',id).select().single();else r=await db.from('products').insert(data).select().single();if(r.error)return $('editMsg').innerHTML='<p class="error">'+esc(r.error.message)+'</p>';id=r.data.id;const rows=[];rows.push({product_id:id,language_code:'it',name:$('name_it').value.trim(),description:$('description_it').value.trim()});langs.filter(x=>x[0]!=='it').forEach(([c])=>{const d=document.querySelector(`[data-lang-desc="${c}"]`).value.trim();if(d)rows.push({product_id:id,language_code:c,name:$('name_it').value.trim(),description:d})});const {error:te}=await db.from('product_translations').upsert(rows,{onConflict:'product_id,language_code'});if(te)return $('editMsg').innerHTML='<p class="error">'+esc(te.message)+'</p>';$('editMsg').innerHTML='<p class="ok">Salvato correttamente.</p>';await load();setTimeout(closeEditor,500)}
$('saveDraft').onclick=()=>save('draft');$('publish').onclick=()=>save('published');$('deleteBtn').onclick=async()=>{if(!current||!confirm('Eliminare definitivamente questa focaccia?'))return;const {error}=await db.from('products').delete().eq('id',current.id);if(error)alert(error.message);else{await load();closeEditor()}};
init();
